
INSERT INTO `books_shop`.`type_product` (`id_type_product`, `name_type_product`) VALUES ('1', 'Business');
INSERT INTO `books_shop`.`type_product` (`id_type_product`, `name_type_product`) VALUES ('2', 'Technology');
INSERT INTO `books_shop`.`type_product` (`id_type_product`, `name_type_product`) VALUES ('3', 'Romantic');
INSERT INTO `books_shop`.`type_product` (`id_type_product`, `name_type_product`) VALUES ('4', 'Adventure');
INSERT INTO `books_shop`.`type_product` (`id_type_product`, `name_type_product`) VALUES ('5', 'Fictional');

INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('1', 'Howdy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner2.jpg', 0, 'Birds Gonna Be Happy', 'France', '45', '2005', 'Kim dong', '10', '1');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('2', 'Howdy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner2.jpg', 0, 'Birds Gonna Be Happy', 'France', '45', '2005', 'Kim dong', '10', '1');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('3', 'Howdy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner2.jpg', 0, 'Birds Gonna Be Happy', 'France', '45', '2005', 'Kim dong', '10', '1');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('4', 'Howdy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner2.jpg', 0, 'Birds Gonna Be Happy', 'France', '45', '2005', 'Kim dong', '10', '1');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('5', 'Howdy', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner2.jpg', 0, 'Birds Gonna Be Happy', 'France', '45', '2005', 'Kim dong', '10', '1');

INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('6', 'Stand', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner1.jpg', 0, 'Life Of The Wild', 'USA', '45', '2004', 'Kim dong', '10', '2');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('7', 'Stand', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner1.jpg', 0, 'Life Of The Wild', 'USA', '45', '2004', 'Kim dong', '10', '2');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('8', 'Stand', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner1.jpg', 0, 'Life Of The Wild', 'USA', '45', '2004', 'Kim dong', '10', '2');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('9', 'Stand', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner1.jpg', 0, 'Life Of The Wild', 'USA', '45', '2004', 'Kim dong', '10', '2');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('10', 'Stand', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/main-banner1.jpg', 0, 'Life Of The Wild', 'USA', '45', '2004', 'Kim dong', '10', '2');

INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('11', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item1.jpg', 0, 'Simple Way Of Piece Life', 'France', '45', '2005', 'Kim dong', '10', '3');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('12', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item1.jpg', 0, 'Simple Way Of Piece Life', 'France', '45', '2005', 'Kim dong', '10', '3');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('13', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item1.jpg', 0, 'Simple Way Of Piece Life', 'France', '45', '2005', 'Kim dong', '10', '3');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('14', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item1.jpg', 0, 'Simple Way Of Piece Life', 'France', '45', '2005', 'Kim dong', '10', '3');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('15', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item1.jpg', 0, 'Simple Way Of Piece Life', 'France', '45', '2005', 'Kim dong', '10', '3');

INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('16', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item2.jpg', 0, 'Great Travel At Desert', 'France', '45', '2005', 'Kim dong', '10', '4');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('17', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item2.jpg', 0, 'Great Travel At Desert', 'France', '45', '2005', 'Kim dong', '10', '4');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('18', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item2.jpg', 0, 'Great Travel At Desert', 'France', '45', '2005', 'Kim dong', '10', '4');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('19', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item2.jpg', 0, 'Great Travel At Desert', 'France', '45', '2005', 'Kim dong', '10', '4');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('20', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item2.jpg', 0, 'Great Travel At Desert', 'France', '45', '2005', 'Kim dong', '10', '4');

INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('21', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item3.jpg', 0, 'The Lady Beauty Scarlett', 'France', '45', '2005', 'Kim dong', '10', '5');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('22', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item3.jpg', 0, 'The Lady Beauty Scarlett', 'France', '45', '2005', 'Kim dong', '10', '5');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('23', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item3.jpg', 0, 'The Lady Beauty Scarlett', 'France', '45', '2005', 'Kim dong', '10', '5');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('24', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item3.jpg', 0, 'The Lady Beauty Scarlett', 'France', '45', '2005', 'Kim dong', '10', '5');
INSERT INTO `books_shop`.`products` (`id_product`, `author`, `describe_book`, `img`, `is_delete`, `name_product`, `nation_book`, `price_book`, `publication_year`, `publishing_company`, `quantity_books`, `id_type_product`) VALUES ('25', 'Phin', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', '/images/product-item3.jpg', 0, 'The Lady Beauty Scarlett', 'France', '45', '2005', 'Kim dong', '10', '5');

